# This is an example Railway config file

# The name of your app
name = "budget-managementa-app"

# The language and version of your app
language = "nodejs@16"

# The port that your app listens on
port = "$PORT"

[build]
builder = "node"
command = "npm run build"

[env]
INSTALL_COMMAND = "npm ci"
START_COMMAND = "npm run start"
NODE_ENV = "production"
REACT_APP_BUDGET_MANAGEMENT_API = "https://budget-management-api.up.railway.app/api"

# The files that should be ignored when deploying
[ignore]
directories = ["node_modules", "build"]
files = [".env", ".env.local"]
