name: Build and push to budget-management-api

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Clone destination repository
        uses: actions/checkout@v2
        with:
          repository: ashotnazaryan/budget-management-api
          token: ${{ secrets.DESTINATION_TOKEN }}
          ref: master
          path: destination

      - name: Delete client folder
        run: |
          rm -rf destination/client

      - name: Copy build folder
        run: cp -R build/. destination/client

      - name: Commit and push changes
        working-directory: ./destination
        run: |
          git config --global user.email "ashotnazaryan45@gmail.com"
          git config --global user.name "anazaryan"
          git add .
          git commit --allow-empty -m "Deploy Build"
          git push origin master
