name: Lighthouse Report

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v10
        with:
          urls: |
            https://budget-management.up.railway.app/dashboard
            https://budget-management.up.railway.app/transactions
            https://budget-management.up.railway.app/accounts
            https://budget-management.up.railway.app/categories
            https://budget-management.up.railway.app/settings
            https://budget-management.up.railway.app/profile
            https://budget-management.up.railway.app/transfers
            https://budget-management.up.railway.app/invoices
            https://budget-management.up.railway.app/reports
            https://budget-management.up.railway.app/charts
            https://budget-management.up.railway.app/login
          budgetPath: ./budget.json
          uploadArtifacts: true
          temporaryPublicStorage: true
